name: Get Feed

on:
  schedule:
    - cron: '0 4 * * *' # 12:00 Beijing Time (UTC+8)
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest

    env:
      NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDS_DATABASE_ID: ${{ secrets.NOTION_FEEDS_DATABASE_ID }}
      RUN_FREQUENCY: 86400

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Update Notion Feed
        run: |
          curl -fsSL \
            https://raw.githubusercontent.com/lieeew/notion-feeder/build/dist/index.js \
            -o index.js
          node index.js
